spring.application.name=${APP_NAME:app_name_not_defined}
app.autor=${STUDENT_NAME:student_name_not_defined}
app.entorno=${APP_ENV:app_env_not_defined}
app.max.users=${MAX_USERS:max_users_not_defined}
app.date=15 De febrero de 2026
app.mi.version=3.4.5
app.my.password=${MY_PASSWORD:password_not_defined}