spring.application.name=starter.test
app.autor=Luis Bernabe
app.mi.version=3.4.5
app.date=10 De febrero de 2026
app.my.password=${MY_PASSWORD:password_not_defined}
app.name=${APP_NAME:no_app_name}
app.env=${APP_ENV:who_knows}
student.name=${STUDENT_NAME:no_name}
max.users=${MAX_USERS:not_specified}