spring.application.name=starter.test
app.autor=Luis Bernabe
app.mi.version=3.4.5
app.date=10 De febrero de 2026
app.my.password=${MY_PASSWORD:password_not_defined}
app.name=${APP_NAME:Proyecto Default}
app.env=${APP_ENV}
app.student.name=${STUDENT_NAME}
app.max.users=${MAX_USERS}